export const GET_USERS_FROM_API = "GET_USERS_FROM_API";
export const DELETE_USER_BY_ID = "DELETE_USER_BY_ID";
export const UPDATE_USER_BY_ID = "UPDATE_USER_BY_ID";
export const GET_USER_BY_ID = "GET_USER_BY_ID";